### ISSUE TITLE
[BUG] Krane can not be installed using FluxCD

### ISSUE THREAD

**Issue by nekwar** [appvia/krane#277]
### Short issue description
It's not possible to install Krane using FluxCD solution because of the following issue:
```
Helm install failed: error while running post render on files: map[string]interface {}(nil): yaml: unmarshal errors: line 51: mapping key "restartPolicy" already defined at line 49
```
Interesting thing is that it works fine with just helm binary.

Krane version: 0.1.1
OS (Linux/Mac/Windows..): MacOS
Kubernetes version: 1.22
Kubernetes distribution (e.g. GKE, EKS, ...): MKE (Mirantis Kubernetes Engine)

### How can we reproduce the issue?
Install FluxCD to your cluster, then add two manifests to FluxCD:
```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: krane
  namespace: krane
spec:
  interval: 5m
  chart:
    spec:
      chart: krane
      version: 0.1.1
      sourceRef:
        kind: HelmRepository
        name: krane-chart
        namespace: krane
      interval: 5m
```
```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: krane-chart
  namespace: krane
spec:
  interval: 1h
  url: https://appvia.github.io/krane
  timeout: 3m
```
### Suggestions on how to fix the issue
The reason for that is duplicate `restartPolicy` option in RedisGraph deployment manifest on lines https://github.com/appvia/krane/blob/master/charts/krane/templates/deployment.yaml#L48 and https://github.com/appvia/krane/blob/master/charts/krane/templates/deployment.yaml#L62. 

I will create PR for that fix
